---
title: "Plots we got rid of"
author: "Sarah Gaichas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Because I'm too lazy to type them again

Commercial diversity  (Fig. \ref{fig:commercial-div})

```{r commercial-div, fig.cap = "Commercial fleet count and diversity in the Mid-Atlantic.", fig.asp=.9}
#, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/human_dimensions_MAB.Rmd-commercial-div.R")

a <- ecodata::plot_commercial_div(report = "MidAtlantic", varName = "Fleet count")

b <- ecodata::plot_commercial_div(report = "MidAtlantic", varName = "Fleet diversity in revenue")

a/b
```

Seasonal surface temperature  (Fig. \ref{fig:seasonal-oisst-anom})

```{r seasonal-oisst-anom, fig.cap="MAB (grey outline) seasonal sea surface temperature (SST) time series . Seasons are defined as: Jan-Mar for winter, Apr-Jun for spring, Jul-Sep for summer, and Oct-Dec for fall.", fig.width = 6, fig.asp = .6}
#overlaid onto 2021 seasonal spatial anomalies, code=readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-seasonal-sst-anom-gridded.R")

#ecodata::plot_seasonal_sst_anomaly_gridded()
ecodata::plot_seasonal_oisst_anom()

```

Seasonal bottom temperature (Fig. \ref{fig:bottom-temp})

```{r bottom-temp, fig.cap="MAB seasonal bottom temperature (BT) anomaly time series. Seasons are defined as: Jan-Mar for winter, Apr-Jun for spring, Jul-Sep for summer, and Oct-Dec for fall.", fig.width = 6, fig.asp = .6}
#The final 2 years of each time series (open circles) are modeled estimates subject to change.", code=readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-bottom-temp-hi-res-ts.R")

ecodata::plot_bottom_temp_comp()
```
